apiVersion: v1
kind: Service
metadata:
  name: survey-backend-service
spec:
  type: NodePort
  selector:
    app: survey-backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001   # backend will be exposed on localhost:30001
