apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: survey-backend
  template:
    metadata:
      labels:
        app: survey-backend
    spec:
      containers:
        - name: survey-backend
          image: aahanjain1411/survey-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
